name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - run : mkdir build && cd build
    - name: Cmake 
      run: cmake .
    - name: make
      run: make 
    #- name: exe
      #run: ../Test.exe
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: "/home/runner/work/test"
