name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
   # - name: configure
    #  run: ../configure
    #- run : mkdir build
    #- run: path = $(pwd)
    #- run : cd build
    - run : mkdir build && cd build
    - name: Cmake 
      run: cmake .
    - name: make
      run: make 
    - name: exe
      run: ./Test.exe
    # - name: make check
     # run: make check
    #- name: make distcheck
      #run: make distcheck
